#ifndef DEFINITIONS_H_INCLUDED
#define DEFINITIONS_H_INCLUDED

#define ANCHO_PERSONAJE 35.0f
#define ALTURA_PERSONAJE 75.0f
#define PERSONAJE_CANT_MOVIMIENTO 50.0f
#define SEPARACION_PARA_PERSONAJE 400.0f

#define ANCHO_TAXI 70.0f
#define ALTURA_TAXI 40.0f
#define TAXI_VEL_MOVIMIENTO_X 0.5f
#define TAXI_VEL_MOVIMIENTO_Y 0.0f
#define SEPARACION_ENTRE_TAXIS 150.0f

#define ANCHO_VENTANA 1330
#define ALTURA_VENTANA 750
#define TITULO_JUEGO "CruzARG"



#endif // DEFINITIONS_H_INCLUDED
