#ifndef DEFINITIONS_H_INCLUDED
#define DEFINITIONS_H_INCLUDED

#define ANCHO_VENTANA 1330
#define ALTURA_VENTANA 750
#define TITULO_JUEGO "CruzARG"

#define ANCHO_BARRERA 60.0f
#define ALTURA_BARRERA 55.0f
#define ESPACIO_ENTRE_CUADRAS 300.0f

#define ANCHO_PERSONAJE 15.0f
#define ALTURA_PERSONAJE 30.0f
#define PERSONAJE_CANT_MOVIMIENTO 30.0f
#define SEPARACION_PARA_PERSONAJE 400.0f

#define ANCHO_TAXI 60.0f
#define ALTURA_TAXI 30.0f
#define TAXI_VEL_MOVIMIENTO_X 0.5f
#define TAXI_VEL_MOVIMIENTO_Y 0.0f

#define ANCHO_AUTO 70.0f
#define ALTURA_AUTO 30.0f
#define AUTO_VEL_MOVIMIENTO_X 0.5f
#define AUTO_VEL_MOVIMIENTO_Y 0.0f

#define ANCHO_COLECTIVO 90.0f
#define ALTURA_COLECTIVO 30.0f
#define COL_VEL_MOVIMIENTO_X 0.8f
#define COL_VEL_MOVIMIENTO_Y 0.0f


#define SEPARACION_ENTRE_VEHICULOS 150.0f

#endif // DEFINITIONS_H_INCLUDED
