#ifndef DEFINITIONS_H_INCLUDED
#define DEFINITIONS_H_INCLUDED

#define ANCHO_PERSONAJE 50.0f
#define ALTURA_PERSONAJE 70.0f
#define PERSONAJE_CANT_MOVIMIENTO 50.0f

#define ANCHO_TAXI 90.0f
#define ALTURA_TAXI 50.0f
#define TAXI_VEL_MOVIMIENTO_X 0.2f
#define TAXI_VEL_MOVIMIENTO_Y 0.0f

#define ANCHO_VENTANA 960
#define ALTURA_VENTANA 540
#define TITULO_JUEGO "CruzARG"



#endif // DEFINITIONS_H_INCLUDED
